### ISSUE TITLE
type Array has no field args for simple property in QuickCheck

### ISSUE THREAD

**Issue by basbossink** [pao/QuickCheck.jl#3]
I'm trying to use the Julia programming language for the first time, so please forgive if I made some horrible beginner mistake. I'm trying to write a simple example using the QuickCheck package. Here is the code:

```
module QuickCheckTest

using QuickCheck


function factorial(n)
  if n < 0
    error("factorial undefined for negative numbers")
  end
  if n == 0
    1
  elseif 0 < n <= 2
    n
  else
    n*factorial(n-1)
  end
end

property((n::Int)->factorial(n)/n == factorial(n-1))

end
```

When I run this using Julia 0.2.0 on my windows 7 machine I get the following error:

```
ERROR: type Array has no field args
 in lambda_arg_types at C:\Users\Bas\Documents\Dropbox\.julia\QuickCheck\src\Qui
ckCheck.jl:16
 in property at C:\Users\Bas\Documents\Dropbox\.julia\QuickCheck\src\QuickCheck.
jl:26
 in include at boot.jl:238
 in include_from_node1 at loading.jl:114
WARNING: backtraces on your platform are often misleading or partially incorrect
```

I feel the above code is similar to the one used in the QuickCheck documentation. The QuickCheck version I'm using is 0.0.0. I have searched the internet but can not find any useful information. Am I doing something wrong here or is this a bug in QuickCheck? Please note that I've also posted this as a question on [StackOverflow](http://stackoverflow.com/questions/21573064/), so any feedback on that question would also be appreciated.

**Comment by pao** [comment]
Probably a bug in QuickCheck--I haven't really put any time into it due to a lack of users, and the last update (except for a recent patch by @astrieanna) was before 0.2 was released. Since I originally wrote it, a number of internal implementation details in Julia have changed, and since QC was using them, it's broken now.

Knowing people are actually interested provides a bit of motivation. I'll see what I can do.

**Comment by basbossink** [comment]
Thanks, I've always liked Haskell's QuickCheck and am just getting started with Julia. I feel a powerful testing tool like QuickCheck is definitely very helpful.

**Comment by pao** [comment]
Looks like #4 works insofar as the error comes from attempting to check the property with no constraints on `n`. But with a conditional property (note to self: we have keywords now, should probably use those):

```
julia> condproperty((n::Int)->factorial(n)/n == factorial(n-1), 100, 100, (x)->x>=1)
ERROR: Falsifiable, after 38 tests:
21

 in error at error.jl:21
 in check_property at /home/patrick/.julia/v0.2/QuickCheck/src/QuickCheck.jl:57
 in condproperty at /home/patrick/.julia/v0.2/QuickCheck/src/QuickCheck.jl:31
 in condproperty at /home/patrick/.julia/v0.2/QuickCheck/src/QuickCheck.jl:33
```
