### ISSUE TITLE
Empty LICENSE.md file

### ISSUE THREAD

**Issue by staticfloat** [pao/QuickCheck.jl#5]
It would be nice to get this release under an opensource license. :)

**Comment by pao** [comment]
Noted. A wonderful example of early Pkg development if I say so myself :D

**Comment by staticfloat** [comment]
Now I'm confused;  It looks like there's a `LICENSE.md` file here just fine; and it was added a year ago!  Am I going insane, or is this the second time I've hallucinated an empty file today....

**Comment by pao** [comment]
I know the file was empty at one point, and I thought I had fixed it when I was working on doc stuff, but I figured it's possible I had missed one.
